environments:
  - name: env1
    nodes:
      - name: node1
        root_node: true
        terminal_node: false
        publishers:
          - name: topic_1M
            msg_size: 1M
            msg_frequency: 25.0
          - name: topic_2M
            bandwidth: 2M
            msg_size: 250K
          - name: topic_500K
            bandwidth: 500K
            msg_frequency: 10.0
      - name: node2
        root_node: false
        terminal_node: false
        publishers:
          - name: topic_1M
            msg_size: 1M
            msg_frequency: 25.0
          - name: topic_2M
            bandwidth: 2M
            msg_size: 250K
          - name: topic_500K
            bandwidth: 500K
            msg_frequency: 10.0
        subscribers:
          - name: topic_1M
            node: node1
          - name: topic_2M
            node: node1
          - name: topic_500K
            node: node1
      - name: node3
        root_node: false
        terminal_node: true
        subscribers:
          - name: topic_1M
            node: node2
          - name: topic_2M
            node: node2
          - name: topic_500K
            node: node2
