environments:
  env1:
    nodes:
      node1:
        root_node: false
        terminal_node: false
        publish_topics:
          topic_1M:
            msg_size: "1M"
            msg_frequency: 25.0
          topic_2M:
            bandwidth: "2M"
            msg_size: "250K"
          topic_500K:
            bandwidth: "500K"
            msg_frequency: 10.0
        subscribe_topics:
          topic_1M:
            node: "node2"
          topic_2M:
            node: "node2"
          topic_500K:
            node: "node2"
      node2:
        root_node: false
        terminal_node: false
        publish_topics:
          topic_1M:
            msg_size: "1M"
            msg_frequency: 25.0
          topic_2M:
            bandwidth: "2M"
            msg_size: "250K"
          topic_500K:
            bandwidth: "500K"
            msg_frequency: 10.0
        subscribe_topics:
          topic_1M:
            node: "node1"
          topic_2M:
            node: "node1"
          topic_500K:
            node: "node1"
