---
environments:
  - name: environment1
    nodes:
      - name: lidar_node
        qty: 2
        root_node: true
        terminal_node: false
        publishers:
          - name: group1
            qty: 1
            bandwidth: 10M
            msg_size: 2M
      - name: lidar_transformer_node
        qty: 1
        root_node: false
        terminal_node: false
        publishers:
          - name: output_topic
            bandwidth: 2M
            frequency: 20.0
