environments:
  - name: env1
    nodes:
      - name: node1
        qty: 2
        root_node: true
        terminal_node: false
        publishers:
          - name: topic_1M
            qty: 1
            msg_size: 1M
            frequency: 25.0
            qos_depth: 1
            qos_policy: reliable
          - name: topic_2M
            qty: 2
            bandwidth: 2M
            msg_size: 250K
            qos_depth: 1
            qos_policy: reliable
          - name: topic_500K
            qty: 3
            bandwidth: 500K
            frequency: 10.0
            qos_depth: 1
            qos_policy: reliable
      - name: node2
        qty: 2
        root_node: false
        terminal_node: false
        publishers:
          - name: topic_1M
            qty: 4
            msg_size: 1M
            frequency: 25.0
            qos_depth: 1
            qos_policy: reliable
          - name: topic_2M
            qty: 5
            bandwidth: 2M
            msg_size: 250K
            qos_depth: 1
            qos_policy: reliable
          - name: topic_500K
            qty: 6
            bandwidth: 500K
            frequency: 10.0
            qos_depth: 1
            qos_policy: reliable
        subscribers:
          - name: topic_1M
            node: node1
          - name: topic_2M_1
            node: node1
          - name: topic_2M_2
            node: node1
          - name: topic_500K_1
            node: node1
          - name: topic_500K_2
            node: node1
          - name: topic_500K_3
            node: node1
      - name: node3
        qty: 2
        root_node: false
        terminal_node: true
        subscribers:
          - name: topic_1M_1
            node: node2
          - name: topic_1M_2
            node: node2
          - name: topic_1M_3
            node: node2
          - name: topic_1M_4
            node: node2
          - name: topic_2M_1
            node: node2
          - name: topic_2M_2
            node: node2
          - name: topic_2M_3
            node: node2
          - name: topic_2M_4
            node: node2
          - name: topic_2M_5
            node: node2
          - name: topic_500K_1
            node: node2
          - name: topic_500K_2
            node: node2
          - name: topic_500K_3
            node: node2
          - name: topic_500K_4
            node: node2
          - name: topic_500K_5
            node: node2
          - name: topic_500K_6
            node: node2
