name: Galactic Workflow

on:
  - pull_request
  - push

jobs:
  build-ros2-galactic:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-desktop-latest
    env:
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: galactic
      - name: Install CycloneDDS
        run: sudo apt-get update && sudo apt-get install -y ros-galactic-rmw-cyclonedds-cpp
      - name: Run Tests
        id: galactic_action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            fabric_interfaces
            fabric_nodes
          target-ros2-distro: galactic
          skip-tests: true
          import-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # This is the default, but added for clarity
          publish_dir: ${{ steps.galactic_action_ros_ci_step.outputs.ros-workspace-directory-name }}/build/fabric_nodes/docs/Doxygen/html
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-galactic
          path: ${{ steps.galactic_action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
