name: Galactic Workflow

on:
  - pull_request
  - push

jobs:
  build-ros2-galactic:
    runs-on: ubuntu-20.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: galactic
      - name: Run Tests
        id: galactic_action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            fabric_interfaces
            fabric_nodes
          target-ros2-distro: galactic
          skip-tests: true
          import-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-galactic
          path: ${{ steps.galactic_action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
