name: ROS2 Build Workflow

on:
  - pull_request
  - push

jobs:
  build-ros2-galactic:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: galactic
          import-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            fabric_interfaces
            fabric_nodes
          target-ros2-distro: galactic
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
  build-ros2-humble:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
          import-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            fabric_interfaces
            fabric_nodes
          target-ros2-distro: humble
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
  build-ros2-iron:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-iron-ros-base-latest
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: iron
          import-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            fabric_interfaces
            fabric_nodes
          target-ros2-distro: iron
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
